---
# Source: mimir-distributed/templates/query-scheduler/query-scheduler-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mimir-query-scheduler
  labels:
    helm.sh/chart: mimir-distributed-6.0.3
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: query-scheduler
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "o11y-metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: query-scheduler
  maxUnavailable: 1
