apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ca
  namespace: kube-system
spec:
  isCA: true
  commonName: Hubble Internal CA
  secretName: hubble-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hubble-ca-issuer
  namespace: kube-system
spec:
  ca:
    secretName: hubble-ca-secret
