apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
  - https://raw.githubusercontent.com/cilium/cilium/v1.18.3/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumloadbalancerippools.yaml
  - https://raw.githubusercontent.com/cilium/cilium/v1.18.3/pkg/k8s/apis/cilium.io/client/crds/v2alpha1/ciliuml2announcementpolicies.yaml
  - ./hubble-ca.yaml
  - ./gatewayclass.yaml
  - ./lb-ip-pool.yaml
  - ./l2announcement-policy.yaml
  - helm/cilium/templates/cilium-agent/clusterrole.yaml
  - helm/cilium/templates/cilium-agent/clusterrolebinding.yaml
  - helm/cilium/templates/cilium-agent/daemonset.yaml
  - helm/cilium/templates/cilium-agent/dashboards-configmap.yaml
  - helm/cilium/templates/cilium-agent/role.yaml
  - helm/cilium/templates/cilium-agent/rolebinding.yaml
  - helm/cilium/templates/cilium-agent/service.yaml
  - helm/cilium/templates/cilium-agent/serviceaccount.yaml
  - helm/cilium/templates/cilium-agent/servicemonitor.yaml
  - helm/cilium/templates/cilium-configmap.yaml
  - helm/cilium/templates/cilium-envoy/configmap.yaml
  - helm/cilium/templates/cilium-envoy/daemonset.yaml
  - helm/cilium/templates/cilium-envoy/service.yaml
  - helm/cilium/templates/cilium-envoy/serviceaccount.yaml
  - helm/cilium/templates/cilium-operator/clusterrole.yaml
  - helm/cilium/templates/cilium-operator/clusterrolebinding.yaml
  - helm/cilium/templates/cilium-operator/deployment.yaml
  - helm/cilium/templates/cilium-operator/role.yaml
  - helm/cilium/templates/cilium-operator/rolebinding.yaml
  - helm/cilium/templates/cilium-operator/service.yaml
  - helm/cilium/templates/cilium-operator/serviceaccount.yaml
  - helm/cilium/templates/cilium-operator/servicemonitor.yaml
  - helm/cilium/templates/cilium-secrets-namespace.yaml
  - helm/cilium/templates/hubble-relay/configmap.yaml
  - helm/cilium/templates/hubble-relay/deployment.yaml
  - helm/cilium/templates/hubble-relay/service.yaml
  - helm/cilium/templates/hubble-relay/serviceaccount.yaml
  - helm/cilium/templates/hubble-ui/clusterrole.yaml
  - helm/cilium/templates/hubble-ui/clusterrolebinding.yaml
  - helm/cilium/templates/hubble-ui/configmap.yaml
  - helm/cilium/templates/hubble-ui/deployment.yaml
  - helm/cilium/templates/hubble-ui/ingress.yaml
  - helm/cilium/templates/hubble-ui/service.yaml
  - helm/cilium/templates/hubble-ui/serviceaccount.yaml
  - helm/cilium/templates/hubble/dashboards-configmap.yaml
  - helm/cilium/templates/hubble/metrics-service.yaml
  - helm/cilium/templates/hubble/peer-service.yaml
  - helm/cilium/templates/hubble/servicemonitor.yaml
  - helm/cilium/templates/hubble/tls-certmanager/relay-client-secret.yaml
  - helm/cilium/templates/hubble/tls-certmanager/server-secret.yaml
