apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y-node-exporter
resources:
  - namespace.yaml
  - helm/prometheus-node-exporter/templates/daemonset.yaml
  - helm/prometheus-node-exporter/templates/service.yaml
  - helm/prometheus-node-exporter/templates/serviceaccount.yaml
  - helm/prometheus-node-exporter/templates/servicemonitor.yaml
