---
apiVersion: v1
kind: Namespace
metadata:
  name: o11y-node-exporter
  labels:
    name: o11y-node-exporter
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
