apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: o11y-collector
spec:
  mode: daemonset

  hostNetwork: false

  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: GOMEMLIMIT
      value: "204MiB"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
      mountPropagation: HostToContainer
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true

  volumes:
    - name: hostfs
      hostPath:
        path: /
    - name: varlogpods
      hostPath:
        path: /var/log/pods

  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    serviceAccount: otel-targetallocator
    prometheusCR:
      enabled: true
      serviceMonitorSelector: {}
      podMonitorSelector: {}

  config:
    exporters:
      otlphttp/loki:
        endpoint: http://loki-gateway.o11y-logs.svc.cluster.local:80/otlp
        tls:
          insecure: true
      otlphttp/mimir:
        endpoint: http://mimir-gateway.o11y-metrics.svc.cluster.local:80/otlp
        tls:
          insecure: true
      otlp/tempo:
        endpoint: tempo-distributor.o11y-traces.svc.cluster.local:9095
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 30s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/o11y-collector_*/*/*.log
          - /var/log/pods/o11y-logs_*/*/*.log
        start_at: end
        include_file_path: true
        include_file_name: false
        operators:
          - type: container
            id: container-parser
            max_log_size: 102400
        retry_on_failure:
          enabled: true
      kubeletstats:
        collection_interval: 20s
        auth_type: serviceAccount
        endpoint: https://${env:K8S_NODE_IP}:10250
        extra_metadata_labels:
          - k8s.volume.type
        metric_groups:
          - container
          - pod
          - node
          - volume
      hostmetrics:
        root_path: /hostfs
        collection_interval: 10s
        scrapers:
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
              system.cpu.logical.count:
                enabled: true
          disk: null
          filesystem:
            exclude_fs_types:
              fs_types:
                - autofs
                - binfmt_misc
                - bpf
                - cgroup2
                - configfs
                - debugfs
                - devpts
                - devtmpfs
                - fusectl
                - hugetlbfs
                - iso9660
                - mqueue
                - nsfs
                - overlay
                - proc
                - procfs
                - pstore
                - rpc_pipefs
                - securityfs
                - selinuxfs
                - squashfs
                - sysfs
                - tracefs
              match_type: strict
            exclude_mount_points:
              match_type: regexp
              mount_points:
                - /dev/*
                - /proc/*
                - /sys/*
                - /run/k3s/containerd/*
                - /var/lib/docker/*
                - /var/lib/kubelet/*
                - /snap/*
            metrics:
              system.filesystem.utilization:
                enabled: true
          load: null
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
              system.memory.limit:
                enabled: true
          network: null
          paging:
            metrics:
              system.paging.utilization:
                enabled: true

    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      k8sattributes:
        passthrough: false
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.start_time
          labels:
            - tag_name: $$1
              key_regex: (.*)
              from: pod
          annotations:
            - tag_name: $$1
              key_regex: (.*)
              from: pod
        filter:
          node_from_env_var: K8S_NODE_NAME
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    service:
      extensions:
        - health_check
      pipelines:
        logs:
          receivers:
            - filelog
          processors:
            - k8sattributes
            - memory_limiter
            - batch
          exporters:
            - otlphttp/loki

        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - prometheus
            - otlp
          processors:
            - k8sattributes
            - memory_limiter
            - batch
          exporters:
            - otlphttp/mimir

        traces:
          receivers:
            - otlp
          processors:
            - k8sattributes
            - memory_limiter
            - batch
          exporters:
            - otlp/tempo
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${env:MY_POD_IP}
                    port: 8888
