---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8scluster
rules:
  # Required for k8scluster receiver - core resources
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - pods
      - services
      - endpoints
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch

  # Required for k8scluster receiver - apps resources
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch

  # Required for k8scluster receiver - batch resources
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch

  # Required for k8scluster receiver - HPA resources
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8scluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8scluster
subjects:
  - kind: ServiceAccount
    name: otel-k8scluster-collector
    namespace: o11y-collector
