apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-k8scluster
  namespace: o11y-collector
spec:
  mode: deployment
  replicas: 1

  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: GOMEMLIMIT
      value: "204MiB"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  config:
    exporters:
      otlphttp/loki:
        endpoint: http://loki-gateway.o11y-logs.svc.cluster.local:80/otlp
        tls:
          insecure: true
      otlphttp/mimir:
        endpoint: http://mimir-gateway.o11y-metrics.svc.cluster.local:80/otlp
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      # Kubernetes cluster-level metrics from API
      k8s_cluster:
        collection_interval: 10s
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
          - NetworkUnavailable
        allocatable_types_to_report:
          - cpu
          - memory
          - storage
          - ephemeral-storage
      k8sobjects:
        objects:
          - exclude_watch_type:
              - DELETED
            group: events.k8s.io
            mode: watch
            name: events
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888

    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

    service:
      extensions:
        - health_check
      pipelines:
        logs:
          receivers:
            - k8sobjects
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlphttp/loki
        metrics:
          receivers:
            - k8s_cluster
            - prometheus
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlphttp/mimir
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${env:MY_POD_IP}
                    port: 8888
