---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for the Rook-Ceph operator
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-ceph-system
  namespace: infra-storage # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.6
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.18.6"
# imagePullSecrets:
#   - name: my-registry-secret
---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for the CephFS CSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace: infra-storage # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.6
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.18.6"
# imagePullSecrets:
#   - name: my-registry-secret
---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for the CephFS CSI provisioner
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace: infra-storage # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.6
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.18.6"
# imagePullSecrets:
#   - name: my-registry-secret
---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for the RBD CSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace: infra-storage # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.6
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.18.6"
# imagePullSecrets:
#   - name: my-registry-secret
---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for the RBD CSI provisioner
kind: ServiceAccount
apiVersion: v1
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace: infra-storage # namespace:operator
  labels:
    operator: rook
    storage-backend: ceph
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: v1.18.6
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/created-by: helm
    helm.sh/chart: "rook-ceph-v1.18.6"
# imagePullSecrets:
#   - name: my-registry-secret
---
# Source: rook-ceph/templates/serviceaccount.yaml
# Service account for Ceph COSI driver
kind: ServiceAccount
apiVersion: v1
metadata:
  name: objectstorage-provisioner
  namespace: infra-storage # namespace:operator
  labels:
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/component: driver-ceph
    app.kubernetes.io/name: cosi-driver-ceph
# imagePullSecrets:
#   - name: my-registry-secret
