apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: o11y
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/ryanseipp/homelab.git
        revision: HEAD
        directories:
          - path: clusters/home/o11y/*
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
    spec:
      project: o11y
      source:
        repoURL: https://github.com/ryanseipp/homelab.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ""
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ServerSideApply=true
