---
# Source: tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tempo-ingester
  namespace: o11y-traces
  labels:
    helm.sh/chart: tempo-distributed-1.53.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: ingester
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: "2.9.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/component: ingester
  maxUnavailable: 1
