---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  namespace: o11y-traces
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo-query-frontend.o11y-traces.svc.cluster.local:3200
        isDefault: false
        editable: false
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - key: service.name
                value: job
              - key: service.namespace
                value: namespace
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            filterByTraceID: true
            filterBySpanID: false
            customQuery: true
            query: '{job="$${__span.tags.job}"} |~ "$${__span.traceId}"'
          tracesToMetrics:
            datasourceUid: mimir
            tags:
              - key: service.name
                value: job
              - key: service.namespace
                value: namespace
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
          serviceMap:
            datasourceUid: mimir
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
          search:
            hide: false
