---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-ctrlplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-nodeplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-controller-manager
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-ctrlplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-nodeplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-ctrlplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
---
# Source: rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-nodeplugin-sa
  labels:
    helm.sh/chart: ceph-csi-operator-0.4.1
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/version: "v0.4.1"
    app.kubernetes.io/managed-by: Helm
  annotations: {}
