apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-storage
resources:
  - namespace.yaml
  - ceph-cluster-dashboard.yaml
  - ceph-osd-dashboard.yaml
  - ceph-pools-dashboard.yaml
  - helm/rook-ceph-cluster/templates/cephblockpool.yaml
  - helm/rook-ceph-cluster/templates/cephcluster.yaml
  - helm/rook-ceph-cluster/templates/cephfilesystem.yaml
  - helm/rook-ceph-cluster/templates/cephobjectstore.yaml
  - helm/rook-ceph-cluster/templates/deployment.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephconnection-crd.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephconnection-viewer-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephconnections-editor-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-r-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-rb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-nodeplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-nodeplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-nodeplugin-r-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/cephfs-nodeplugin-rb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofile-crd.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofile-viewer-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofilemapping-crd.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofilemapping-editor-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofilemapping-viewer-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/clientprofiles-editor-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/deployment.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/driver-crd.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/driver-editor-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/driver-viewer-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/leader-election-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/manager-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/metrics-auth-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/metrics-reader-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/nfs-ctrlplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/nfs-ctrlplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/nfs-nodeplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/nfs-nodeplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/operatorconfig-crd.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/operatorconfig-editor-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/operatorconfig-viewer-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-ctrlplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-ctrlplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-ctrlplugin-r-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-ctrlplugin-rb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-nodeplugin-cr-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-nodeplugin-crb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-nodeplugin-r-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/rbd-nodeplugin-rb-rbac.yaml
  - helm/rook-ceph/charts/ceph-csi-operator/templates/serviceaccount.yaml
  - helm/rook-ceph/templates/cluster-rbac.yaml
  - helm/rook-ceph/templates/clusterrole.yaml
  - helm/rook-ceph/templates/clusterrolebinding.yaml
  - helm/rook-ceph/templates/configmap.yaml
  - helm/rook-ceph/templates/deployment.yaml
  - helm/rook-ceph/templates/resources.yaml
  - helm/rook-ceph/templates/role.yaml
  - helm/rook-ceph/templates/rolebinding.yaml
  - helm/rook-ceph/templates/serviceaccount.yaml
