apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y-kube-state-metrics
resources:
  - namespace.yaml
  - helm/kube-state-metrics/templates/clusterrolebinding.yaml
  - helm/kube-state-metrics/templates/deployment.yaml
  - helm/kube-state-metrics/templates/role.yaml
  - helm/kube-state-metrics/templates/service.yaml
  - helm/kube-state-metrics/templates/serviceaccount.yaml
  - helm/kube-state-metrics/templates/servicemonitor.yaml
