---
apiVersion: v1
kind: Namespace
metadata:
  name: o11y-kube-state-metrics
  labels:
    name: o11y-kube-state-metrics
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
