---
# Source: mimir-distributed/templates/overrides-exporter/overrides-exporter-servmon.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir-overrides-exporter
  namespace: "o11y-metrics"
  labels:
    helm.sh/chart: mimir-distributed-6.0.3
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/component: overrides-exporter
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  namespaceSelector:
    matchNames:
      - o11y-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/component: overrides-exporter
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      relabelings:
        - action: replace
          sourceLabels: [job]
          replacement: "o11y-metrics/overrides-exporter"
          targetLabel: job
        - action: replace
          replacement: "mimir"
          targetLabel: cluster
      scheme: http
