---
# Source: argo-cd/charts/redis-ha/templates/redis-ha-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis-ha
  namespace: "infra-argocd"
  labels:
    heritage: Helm
    release: argocd
    chart: redis-ha-4.34.11
    app: argocd-redis-ha
secrets:
  - name: argocd-redis
