---
# Source: argo-cd/charts/redis-ha/templates/redis-haproxy-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-redis-ha-haproxy
  namespace: "infra-argocd"
  labels:
    app: redis-ha
    heritage: "Helm"
    release: "argocd"
    chart: redis-ha-4.34.11
    component: haproxy
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
