---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: o11y-logs
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.o11y-logs.svc.cluster.local:80
        isDefault: false
        editable: false
        jsonData:
          timeout: 60
          maxLines: 1000
          derivedFields:
            - name: TraceID
              matcherRegex: "trace_id=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: tempo
              urlDisplayLabel: "View Trace"
